// Post Action Types
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_POST_DETAIL_REQUEST = 'FETCH_POST_DETAIL_REQUEST';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS';
export const FETCH_POST_DETAIL_FAILURE = 'FETCH_POST_DETAIL_FAILURE';

export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';

export const SEARCH_POSTS_REQUEST = 'SEARCH_POSTS_REQUEST';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
export const SEARCH_POSTS_FAILURE = 'SEARCH_POSTS_FAILURE';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

// Comment Action Types
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';

// Subreddit Action Types
export const SET_SELECTED_SUBREDDIT = 'SET_SELECTED_SUBREDDIT';

// Sorting Action Types
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_TIME_RANGE = 'SET_TIME_RANGE';
export const SORT_BY_VIRAL = 'SORT_BY_VIRAL';

// UI Action Types
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';